-- ============================================================
-- ATTENDANCE MANAGEMENT SYSTEM DATABASE SCHEMA
-- ============================================================
-- Schema: attendance
-- Dependencies: public schema (employees, organizations, job_titles)
-- Framework: Spring Boot với Spring Data JPA Auditing
-- 
-- WiFi Validation Features:
-- - Support both SSID + BSSID validation for enhanced security
-- - Flexible validation modes: strict, ssid_only, gps_only
-- - Anti-fraud detection with device tracking
-- ============================================================

-- Create attendance schema
CREATE SCHEMA IF NOT EXISTS attendance;

-- ============================================================
-- ENUM TYPES
-- ============================================================

CREATE TYPE attendance.assignment_type AS ENUM ('department', 'position', 'employee');
CREATE TYPE attendance.device_type AS ENUM ('fingerprint', 'face');
CREATE TYPE attendance.device_status AS ENUM ('online', 'offline', 'maintenance');
CREATE TYPE attendance.check_source AS ENUM ('app', 'device');
CREATE TYPE attendance.attendance_status AS ENUM ('normal', 'late', 'early_leave', 'incomplete', 'absent');
CREATE TYPE attendance.exception_type AS ENUM ('late', 'early_leave', 'missing_checkout', 'location_error', 'other');
CREATE TYPE attendance.approval_status AS ENUM ('pending', 'approved', 'rejected', 'cancelled');
CREATE TYPE attendance.summary_status AS ENUM ('draft', 'locked', 'payroll_sent');
CREATE TYPE attendance.risk_level AS ENUM ('low', 'medium', 'high');

-- Create additional enum types used in preapprovals table
CREATE TYPE attendance.preapproval_request_type AS ENUM (
    'late_arrival', 'early_leave', 'schedule_adjustment', 
    'extended_break', 'location_change', 'overtime_request'
);
CREATE TYPE attendance.urgency_level AS ENUM ('low', 'normal', 'high', 'emergency');

-- ============================================================
-- 1. WORKPLACE LOCATIONS - Địa điểm làm việc
-- ============================================================

CREATE TABLE attendance.workplace_locations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    address TEXT,
    latitude DECIMAL(10,8),
    longitude DECIMAL(11,8),
    gps_radius_meters INTEGER DEFAULT 100,
    allowed_wifi_networks JSONB DEFAULT '{"networks":[],"validation_mode":"flexible"}'::jsonb,
    require_gps BOOLEAN DEFAULT true,
    require_wifi BOOLEAN DEFAULT false,
    timezone VARCHAR(50) DEFAULT 'Asia/Ho_Chi_Minh',
    is_active BOOLEAN DEFAULT true,
    
    -- Spring Boot Audit columns
    created_by VARCHAR(50),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_by VARCHAR(50),
    last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 2. WORK SHIFTS - Ca làm việc
-- ============================================================

CREATE TABLE attendance.work_shifts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    days_of_week JSONB DEFAULT '[1,2,3,4,5]'::jsonb,
    late_threshold_minutes INTEGER DEFAULT 15,
    early_leave_threshold_minutes INTEGER DEFAULT 15,
    overtime_threshold_minutes INTEGER DEFAULT 30,
    is_overnight BOOLEAN DEFAULT false,
    is_active BOOLEAN DEFAULT true,
    
    -- Spring Boot Audit columns
    created_by VARCHAR(50),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_by VARCHAR(50),
    last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 3. SHIFT ASSIGNMENTS - Phân ca làm việc
-- ============================================================

CREATE TABLE attendance.shift_assignments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_type attendance.assignment_type NOT NULL,
    target_id INTEGER NOT NULL,
    shift_id INTEGER NOT NULL REFERENCES attendance.work_shifts(id),
    location_id INTEGER NOT NULL REFERENCES attendance.workplace_locations(id),
    effective_from DATE NOT NULL DEFAULT CURRENT_DATE,
    effective_to DATE,
    priority INTEGER DEFAULT 3,
    is_active BOOLEAN DEFAULT true,
    
    -- Spring Boot Audit columns
    created_by VARCHAR(50),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_by VARCHAR(50),
    last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 4. SHIFT EXCEPTIONS - Ngoại lệ ca làm việc
-- ============================================================

CREATE TABLE attendance.shift_exceptions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id INTEGER NOT NULL REFERENCES attendance.shift_assignments(id),
    exception_date DATE NOT NULL,
    new_shift_id INTEGER REFERENCES attendance.work_shifts(id),
    new_location_id INTEGER REFERENCES attendance.workplace_locations(id),
    reason VARCHAR(200),
    status attendance.approval_status DEFAULT 'pending',
    approved_by INTEGER,
    approved_at TIMESTAMP,
    
    -- Spring Boot Audit columns
    created_by VARCHAR(50),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_by VARCHAR(50),
    last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 5. ATTENDANCE DEVICES - Thiết bị chấm công
-- ============================================================

CREATE TABLE attendance.attendance_devices (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    device_code VARCHAR(50) NOT NULL UNIQUE,
    device_type attendance.device_type NOT NULL,
    location_id INTEGER NOT NULL REFERENCES attendance.workplace_locations(id),
    ip_address INET,
    mac_address VARCHAR(17),
    status attendance.device_status DEFAULT 'offline',
    firmware_version VARCHAR(20),
    last_sync_at TIMESTAMP,
    is_active BOOLEAN DEFAULT true,
    
    -- Spring Boot Audit columns
    created_by VARCHAR(50),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_by VARCHAR(50),
    last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 6. ATTENDANCE SESSIONS - Phiên chấm công (check-in/check-out pairs)
-- ============================================================

CREATE TABLE attendance.attendance_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INTEGER NOT NULL,
    work_date DATE NOT NULL,
    session_type VARCHAR(20) DEFAULT 'work',
    check_in_time TIMESTAMP NOT NULL,
    check_out_time TIMESTAMP,
    location_id INTEGER REFERENCES attendance.workplace_locations(id),
    
    -- Link to shift and status
    shift_id INTEGER REFERENCES attendance.work_shifts(id),
    status VARCHAR(20) DEFAULT 'active',
    is_pre_approved BOOLEAN DEFAULT false,
    work_duration_minutes INTEGER,
    
    -- Link to device logs
    check_in_device_log_id BIGINT,
    check_out_device_log_id BIGINT,
    
    -- Calculated fields
    duration_minutes INTEGER GENERATED ALWAYS AS (
        CASE 
            WHEN check_out_time IS NOT NULL THEN 
                EXTRACT(EPOCH FROM (check_out_time - check_in_time))/60
            ELSE NULL
        END
    ) STORED,
    
    -- Validation
    is_validated BOOLEAN DEFAULT false,
    validated_by INTEGER,
    validated_at TIMESTAMP,
    notes TEXT,
    
    -- Spring Boot Audit columns
    created_by VARCHAR(50),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_by VARCHAR(50),
    last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE attendance.attendance_sessions IS 'Từng phiên chấm công - cặp check-in/check-out riêng biệt';
COMMENT ON COLUMN attendance.attendance_sessions.session_type IS 'Loại phiên: work, break, overtime, meeting';

-- ============================================================
-- 7. ATTENDANCE RECORDS - Bản ghi chấm công chính
-- ============================================================

CREATE TABLE attendance.attendance_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INTEGER NOT NULL,
    work_date DATE NOT NULL,
    shift_id INTEGER REFERENCES attendance.work_shifts(id),
    location_id INTEGER REFERENCES attendance.workplace_locations(id),
    
    -- Thời gian dự kiến và thực tế
    planned_check_in TIMESTAMP,
    planned_check_out TIMESTAMP,
    actual_check_in TIMESTAMP,
    actual_check_out TIMESTAMP,
    
    -- Nguồn chấm công
    check_in_source attendance.check_source,
    check_out_source attendance.check_source,
    
    -- Dữ liệu từ app mobile
    check_in_gps_lat DECIMAL(10,8),
    check_in_gps_lng DECIMAL(11,8),
    check_in_wifi_data JSONB,  -- {"ssid": "WIFI_NAME", "bssid": "AA:BB:CC:DD:EE:FF", "validated": true}
    check_out_wifi_data JSONB, -- {"ssid": "WIFI_NAME", "bssid": "AA:BB:CC:DD:EE:FF", "validated": true}
    mobile_device_info JSONB,
    
    -- Dữ liệu từ máy chấm công
    check_in_device_id INTEGER REFERENCES attendance.attendance_devices(id),
    check_out_device_id INTEGER REFERENCES attendance.attendance_devices(id),
    biometric_quality_score INTEGER,
    
    -- Tính toán thời gian
    total_work_minutes INTEGER DEFAULT 0,
    overtime_minutes INTEGER DEFAULT 0,
    late_minutes INTEGER DEFAULT 0,
    early_leave_minutes INTEGER DEFAULT 0,
    break_minutes INTEGER DEFAULT 0,
    
    -- Trạng thái và validation
    status attendance.attendance_status DEFAULT 'normal',
    is_validated BOOLEAN DEFAULT false,
    validated_by INTEGER,
    validated_at TIMESTAMP,
    notes TEXT,
    
    -- Spring Boot Audit columns
    created_by VARCHAR(50),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_by VARCHAR(50),
    last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Constraints
    CONSTRAINT unique_employee_work_date UNIQUE (employee_id, work_date)
);

-- ============================================================
-- 8. LEAVE TYPES - Loại nghỉ phép
-- ============================================================

CREATE TABLE attendance.leave_types (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(10) NOT NULL UNIQUE,
    max_days_per_year INTEGER DEFAULT 0,
    is_paid BOOLEAN DEFAULT true,
    requires_approval BOOLEAN DEFAULT true,
    advance_notice_days INTEGER DEFAULT 1,
    color_code VARCHAR(7) DEFAULT '#3498db',
    is_active BOOLEAN DEFAULT true,
    
    -- Spring Boot Audit columns
    created_by VARCHAR(50),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_by VARCHAR(50),
    last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 9. LEAVE REQUESTS - Đơn xin nghỉ
-- ============================================================

CREATE TABLE attendance.leave_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INTEGER NOT NULL,
    leave_type_id INTEGER NOT NULL REFERENCES attendance.leave_types(id),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    total_days DECIMAL(3,1) NOT NULL,
    reason TEXT,
    supporting_documents JSONB DEFAULT '[]'::jsonb,
    emergency_contact VARCHAR(200),
    work_handover TEXT,
    status attendance.approval_status DEFAULT 'pending',
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    approved_by INTEGER,
    approved_at TIMESTAMP,
    approver_comments TEXT,
    
    -- Spring Boot Audit columns
    created_by VARCHAR(50),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_by VARCHAR(50),
    last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 10. LEAVE BALANCES - Số dư nghỉ phép
-- ============================================================

CREATE TABLE attendance.leave_balances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INTEGER NOT NULL,
    leave_type_id INTEGER NOT NULL REFERENCES attendance.leave_types(id),
    year INTEGER NOT NULL,
    total_entitled DECIMAL(4,1) DEFAULT 0,
    used_days DECIMAL(4,1) DEFAULT 0,
    pending_days DECIMAL(4,1) DEFAULT 0,
    remaining_days DECIMAL(4,1) GENERATED ALWAYS AS (total_entitled - used_days - pending_days) STORED,
    
    -- Spring Boot Audit columns  
    created_by VARCHAR(50),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_by VARCHAR(50),
    last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Constraints
    CONSTRAINT unique_employee_leave_type_year UNIQUE (employee_id, leave_type_id, year)
);

-- ============================================================
-- 11. ATTENDANCE EXCEPTIONS - Giải trình chấm công
-- ============================================================

CREATE TABLE attendance.attendance_exceptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attendance_record_id BIGINT NOT NULL REFERENCES attendance.attendance_records(id),
    employee_id INTEGER NOT NULL,
    exception_type attendance.exception_type NOT NULL,
    employee_explanation TEXT NOT NULL,
    supporting_files JSONB DEFAULT '[]'::jsonb,
    status attendance.approval_status DEFAULT 'pending',
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    reviewed_by INTEGER,
    reviewed_at TIMESTAMP,
    reviewer_comments TEXT,
    
    -- Spring Boot Audit columns
    created_by VARCHAR(50),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_by VARCHAR(50),
    last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 12. ATTENDANCE ADJUSTMENTS - Điều chỉnh chấm công
-- ============================================================

CREATE TABLE attendance.attendance_adjustments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attendance_record_id BIGINT NOT NULL REFERENCES attendance.attendance_records(id),
    field_name VARCHAR(50) NOT NULL,
    old_value TEXT,
    new_value TEXT,
    reason TEXT NOT NULL,
    adjusted_by INTEGER NOT NULL,
    adjusted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN DEFAULT true,
    
    -- Spring Boot Audit columns
    created_by VARCHAR(50),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_by VARCHAR(50),
    last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 13. MONTHLY ATTENDANCE SUMMARIES - Chốt công hàng tháng
-- ============================================================

CREATE TABLE attendance.monthly_attendance_summaries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INTEGER NOT NULL,
    year INTEGER NOT NULL,
    month INTEGER NOT NULL CHECK (month BETWEEN 1 AND 12),
    
    -- Thống kê ngày làm việc
    total_work_days INTEGER DEFAULT 0,
    actual_work_days INTEGER DEFAULT 0,
    present_days INTEGER DEFAULT 0,
    absent_days INTEGER DEFAULT 0,
    late_days INTEGER DEFAULT 0,
    early_leave_days INTEGER DEFAULT 0,
    
    -- Thống kê thời gian
    total_work_hours DECIMAL(6,2) DEFAULT 0,
    overtime_hours DECIMAL(6,2) DEFAULT 0,
    leave_days_by_type JSONB DEFAULT '{}'::jsonb,
    
    -- Tỷ lệ
    attendance_rate DECIMAL(5,2) DEFAULT 0,
    punctuality_rate DECIMAL(5,2) DEFAULT 0,
    
    -- Tính lương
    deduction_amount DECIMAL(12,2) DEFAULT 0,
    overtime_amount DECIMAL(12,2) DEFAULT 0,
    bonus_amount DECIMAL(12,2) DEFAULT 0,
    
    -- Trạng thái chốt
    status attendance.summary_status DEFAULT 'draft',
    locked_by INTEGER,
    locked_at TIMESTAMP,
    payroll_exported_at TIMESTAMP,
    
    -- Spring Boot Audit columns
    created_by VARCHAR(50),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_by VARCHAR(50),
    last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Constraints
    CONSTRAINT unique_employee_year_month UNIQUE (employee_id, year, month)
);

-- ============================================================
-- 14. DEVICE LOGS - Log thiết bị chi tiết
-- ============================================================

CREATE TABLE attendance.device_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INTEGER NOT NULL,
    device_type VARCHAR(20) NOT NULL,
    device_identifier VARCHAR(100) NOT NULL,
    action_timestamp TIMESTAMP NOT NULL,
    action_type VARCHAR(20) NOT NULL,
    
    -- Dedicated GPS columns
    latitude DECIMAL(10,8),
    longitude DECIMAL(11,8),
    gps_accuracy DECIMAL(6,2),
    
    -- Dedicated WiFi columns
    wifi_ssid VARCHAR(100),
    wifi_bssid VARCHAR(17),
    
    -- Dedicated tracking columns
    source VARCHAR(20),
    action VARCHAR(20),
    session_id BIGINT,
    
    -- Legacy JSON fields (for backward compatibility)
    location_data JSONB,
    device_info JSONB,
    validation_result JSONB,
    suspicious_flags JSONB DEFAULT '[]'::jsonb,
    risk_score INTEGER DEFAULT 0,
    
    -- Timestamp và audit columns
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by TEXT DEFAULT 'system',
    last_modified_by TEXT DEFAULT 'system',
    last_modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE attendance.device_logs IS 'Chi tiết thiết bị và vị trí cho từng lần chấm công';
COMMENT ON COLUMN attendance.device_logs.session_id IS 'Liên kết với attendance_sessions (BIGINT)';
COMMENT ON COLUMN attendance.device_logs.source IS 'Nguồn: app, device, manual';
COMMENT ON COLUMN attendance.device_logs.action IS 'Hành động: check_in, check_out';
COMMENT ON COLUMN attendance.device_logs.created_by IS 'Người/hệ thống tạo record';
COMMENT ON COLUMN attendance.device_logs.last_modified_by IS 'Người/hệ thống sửa record cuối cùng';

-- ============================================================
-- 15. SUSPICIOUS ACTIVITIES - Hoạt động khả nghi
-- ============================================================

CREATE TABLE attendance.suspicious_activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INTEGER NOT NULL,
    detection_date DATE NOT NULL,
    activity_type VARCHAR(50) NOT NULL,
    description TEXT NOT NULL,
    evidence_data JSONB,
    risk_level attendance.risk_level DEFAULT 'low',
    status VARCHAR(20) DEFAULT 'pending',
    investigated_by INTEGER,
    investigated_at TIMESTAMP,
    resolution_notes TEXT,
    
    -- Spring Boot Audit columns
    created_by VARCHAR(50),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_by VARCHAR(50),
    last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 16. PUBLIC HOLIDAYS - Ngày nghỉ lễ, tết
-- ============================================================

CREATE TABLE attendance.public_holidays (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    holiday_date DATE NOT NULL,
    holiday_type VARCHAR(50) DEFAULT 'national',
    is_paid BOOLEAN DEFAULT true,
    overtime_rate DECIMAL(4,2) DEFAULT 2.00,
    applies_to_locations JSONB DEFAULT '[]'::jsonb,
    description TEXT,
    is_active BOOLEAN DEFAULT true,
    
    -- Spring Boot Audit columns
    created_by VARCHAR(50),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_by VARCHAR(50),
    last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Constraints
    CONSTRAINT unique_holiday_date_type UNIQUE (holiday_date, holiday_type)
);

COMMENT ON TABLE attendance.public_holidays IS 'Danh sách ngày nghỉ lễ, tết và ngày nghỉ đặc biệt của công ty';
COMMENT ON COLUMN attendance.public_holidays.holiday_type IS 'Loại nghỉ lễ: national (quốc gia), company (công ty), regional (địa phương)';
COMMENT ON COLUMN attendance.public_holidays.overtime_rate IS 'Tỷ lệ lương làm thêm ngày lễ (2.0 = 200%, 3.0 = 300%)';
COMMENT ON COLUMN attendance.public_holidays.applies_to_locations IS 'JSON array các location_id áp dụng, [] = tất cả địa điểm';

-- ============================================================
-- 17. ATTENDANCE PREAPPROVALS - Xin phép trước khi chấm công
-- ============================================================

CREATE TABLE attendance.attendance_preapprovals (
    id BIGSERIAL PRIMARY KEY,
    employee_id INTEGER NOT NULL,
    request_type attendance.preapproval_request_type NOT NULL,
    requested_date DATE NOT NULL,
    
    -- Chi tiết thời gian
    original_check_in TIME,
    requested_check_in TIME,
    original_check_out TIME,
    requested_check_out TIME,
    
    -- Thời gian nghỉ giữa ca (cho extended_break)
    break_start_time TIME,
    break_end_time TIME,
    
    -- Thay đổi địa điểm (cho location_change)
    original_location_id INTEGER REFERENCES attendance.workplace_locations(id),
    requested_location_id INTEGER REFERENCES attendance.workplace_locations(id),
    
    -- Lý do và chứng từ
    reason TEXT NOT NULL,
    supporting_documents JSONB DEFAULT '[]'::jsonb,
    urgency_level attendance.urgency_level DEFAULT 'normal',
    
    -- Workflow approval
    status attendance.approval_status DEFAULT 'pending',
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    approved_by INTEGER,
    approved_at TIMESTAMP,
    approver_comments TEXT,
    
    -- Điều chỉnh tự động
    auto_adjust_attendance BOOLEAN DEFAULT true,
    adjustment_applied BOOLEAN DEFAULT false,
    applied_at TIMESTAMP,
    
    -- Spring Boot Audit columns
    created_by VARCHAR(50),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_by VARCHAR(50),
    last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);



COMMENT ON TABLE attendance.attendance_preapprovals IS 'Xin phép trước khi chấm công (đi muộn, về sớm, đổi vị trí, nghỉ giữa ca)';
COMMENT ON COLUMN attendance.attendance_preapprovals.request_type IS 'Loại xin phép: late_arrival, early_leave, schedule_adjustment, extended_break, location_change, overtime_request';
COMMENT ON COLUMN attendance.attendance_preapprovals.urgency_level IS 'Mức độ khẩn cấp: low, normal, high, emergency';
COMMENT ON COLUMN attendance.attendance_preapprovals.supporting_documents IS 'JSON array chứa danh sách file đính kèm chứng minh';
COMMENT ON COLUMN attendance.attendance_preapprovals.auto_adjust_attendance IS 'Tự động điều chỉnh attendance record khi được duyệt';

-- ============================================================
-- 18. ATTENDANCE SETTINGS - Cấu hình hệ thống
-- ============================================================

CREATE TABLE attendance.attendance_settings (
    setting_key VARCHAR(100) PRIMARY KEY,
    setting_value JSONB NOT NULL,
    description TEXT,
    
    -- Spring Boot Audit columns
    created_by VARCHAR(50),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_by VARCHAR(50),
    last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- FOREIGN KEY CONSTRAINTS TO PUBLIC SCHEMA
-- ============================================================

-- References to public.employees (primary key is 'id', not 'emp_id')
ALTER TABLE attendance.shift_assignments 
ADD CONSTRAINT fk_shift_assignment_employee 
FOREIGN KEY (target_id) REFERENCES public.employees(id) 
DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE attendance.attendance_sessions 
ADD CONSTRAINT fk_session_employee 
FOREIGN KEY (employee_id) REFERENCES public.employees(id);

ALTER TABLE attendance.attendance_records 
ADD CONSTRAINT fk_attendance_employee 
FOREIGN KEY (employee_id) REFERENCES public.employees(id);

ALTER TABLE attendance.leave_requests 
ADD CONSTRAINT fk_leave_request_employee 
FOREIGN KEY (employee_id) REFERENCES public.employees(id);

ALTER TABLE attendance.leave_balances 
ADD CONSTRAINT fk_leave_balance_employee 
FOREIGN KEY (employee_id) REFERENCES public.employees(id);

ALTER TABLE attendance.attendance_exceptions 
ADD CONSTRAINT fk_exception_employee 
FOREIGN KEY (employee_id) REFERENCES public.employees(id);

ALTER TABLE attendance.monthly_attendance_summaries 
ADD CONSTRAINT fk_summary_employee 
FOREIGN KEY (employee_id) REFERENCES public.employees(id);

ALTER TABLE attendance.device_logs 
ADD CONSTRAINT fk_device_log_employee 
FOREIGN KEY (employee_id) REFERENCES public.employees(id);

ALTER TABLE attendance.suspicious_activities 
ADD CONSTRAINT fk_suspicious_employee 
FOREIGN KEY (employee_id) REFERENCES public.employees(id);

ALTER TABLE attendance.attendance_preapprovals 
ADD CONSTRAINT fk_preapproval_employee 
FOREIGN KEY (employee_id) REFERENCES public.employees(id);

-- Add approved_by and reviewed_by foreign key references
ALTER TABLE attendance.shift_exceptions
ADD CONSTRAINT fk_shift_exception_approved_by
FOREIGN KEY (approved_by) REFERENCES public.employees(id);

ALTER TABLE attendance.leave_requests
ADD CONSTRAINT fk_leave_request_approved_by
FOREIGN KEY (approved_by) REFERENCES public.employees(id);

ALTER TABLE attendance.attendance_exceptions
ADD CONSTRAINT fk_attendance_exception_reviewed_by
FOREIGN KEY (reviewed_by) REFERENCES public.employees(id);

ALTER TABLE attendance.attendance_adjustments
ADD CONSTRAINT fk_attendance_adjustment_adjusted_by
FOREIGN KEY (adjusted_by) REFERENCES public.employees(id);

ALTER TABLE attendance.monthly_attendance_summaries
ADD CONSTRAINT fk_summary_locked_by
FOREIGN KEY (locked_by) REFERENCES public.employees(id);

ALTER TABLE attendance.suspicious_activities
ADD CONSTRAINT fk_suspicious_investigated_by
FOREIGN KEY (investigated_by) REFERENCES public.employees(id);

ALTER TABLE attendance.attendance_preapprovals
ADD CONSTRAINT fk_preapproval_approved_by
FOREIGN KEY (approved_by) REFERENCES public.employees(id);

-- Additional validations columns foreign keys
ALTER TABLE attendance.attendance_sessions
ADD CONSTRAINT fk_session_validated_by
FOREIGN KEY (validated_by) REFERENCES public.employees(id);

ALTER TABLE attendance.attendance_records
ADD CONSTRAINT fk_attendance_validated_by
FOREIGN KEY (validated_by) REFERENCES public.employees(id);

-- ============================================================
-- INDEXES FOR PERFORMANCE
-- ============================================================

-- Attendance sessions indexes
CREATE INDEX idx_sessions_employee_date ON attendance.attendance_sessions (employee_id, work_date);
CREATE INDEX idx_sessions_check_in_time ON attendance.attendance_sessions (check_in_time);
CREATE INDEX idx_sessions_incomplete ON attendance.attendance_sessions (employee_id, work_date) WHERE check_out_time IS NULL;
CREATE INDEX idx_sessions_status ON attendance.attendance_sessions (status, work_date);
CREATE INDEX idx_sessions_shift ON attendance.attendance_sessions (shift_id, work_date);
CREATE INDEX idx_sessions_preapproved ON attendance.attendance_sessions (is_pre_approved, work_date) WHERE is_pre_approved = true;

-- Attendance records indexes
CREATE INDEX idx_attendance_employee_date ON attendance.attendance_records (employee_id, work_date);
CREATE INDEX idx_attendance_date_status ON attendance.attendance_records (work_date, status);
CREATE INDEX idx_attendance_location_date ON attendance.attendance_records (location_id, work_date);

-- Shift assignments indexes
CREATE INDEX idx_shift_assignment_type_target ON attendance.shift_assignments (assignment_type, target_id);
CREATE INDEX idx_shift_assignment_effective ON attendance.shift_assignments (effective_from, effective_to);

-- Leave requests indexes
CREATE INDEX idx_leave_requests_employee ON attendance.leave_requests (employee_id, status);
CREATE INDEX idx_leave_requests_date_range ON attendance.leave_requests (start_date, end_date);

-- Device logs indexes
CREATE INDEX idx_device_logs_employee_time ON attendance.device_logs (employee_id, action_timestamp);
CREATE INDEX idx_device_logs_risk ON attendance.device_logs (risk_score DESC, action_timestamp);
CREATE INDEX idx_device_logs_location ON attendance.device_logs (latitude, longitude) WHERE latitude IS NOT NULL;
CREATE INDEX idx_device_logs_wifi ON attendance.device_logs (wifi_ssid, wifi_bssid) WHERE wifi_ssid IS NOT NULL;
CREATE INDEX idx_device_logs_session ON attendance.device_logs (session_id) WHERE session_id IS NOT NULL;
CREATE INDEX idx_device_logs_audit ON attendance.device_logs (created_by, last_modified_by, last_modified_at);

-- Monthly summaries indexes
CREATE INDEX idx_monthly_summary_employee ON attendance.monthly_attendance_summaries (employee_id, year, month);

-- Public holidays indexes
CREATE INDEX idx_holidays_date ON attendance.public_holidays (holiday_date);
CREATE INDEX idx_holidays_type_date ON attendance.public_holidays (holiday_type, holiday_date);
CREATE INDEX idx_holidays_active_date ON attendance.public_holidays (holiday_date, is_active) WHERE is_active = true;

-- Preapprovals indexes
CREATE INDEX idx_preapprovals_employee_date ON attendance.attendance_preapprovals (employee_id, requested_date);
CREATE INDEX idx_preapprovals_status ON attendance.attendance_preapprovals (status, submitted_at);
CREATE INDEX idx_preapprovals_pending ON attendance.attendance_preapprovals (employee_id, status) WHERE status = 'pending';
CREATE INDEX idx_preapprovals_unapplied ON attendance.attendance_preapprovals (requested_date, adjustment_applied) WHERE adjustment_applied = false;

-- ============================================================
-- SAMPLE DATA
-- ============================================================

-- Sample workplace locations
INSERT INTO attendance.workplace_locations (name, address, latitude, longitude, gps_radius_meters, allowed_wifi_networks) VALUES
('Văn phòng chính', 'Số 1 Lý Thường Kiệt, Hoàn Kiếm, Hà Nội', 21.0285, 105.8542, 100, 
 '{
   "networks": [
     {"ssid": "COMPANY_WIFI_5G", "bssid": "AA:BB:CC:DD:EE:01", "description": "Router tầng 1", "require_bssid": true},
     {"ssid": "COMPANY_WIFI_5G", "bssid": "AA:BB:CC:DD:EE:02", "description": "Router tầng 2", "require_bssid": true},
     {"ssid": "COMPANY_GUEST", "bssid": "AA:BB:CC:DD:EE:03", "description": "WiFi khách", "require_bssid": false}
   ],
   "validation_mode": "strict"
 }'),
('Chi nhánh TP.HCM', 'Số 123 Nguyễn Huệ, Q1, TP.HCM', 10.7769, 106.7009, 150,
 '{
   "networks": [
     {"ssid": "HCM_OFFICE_WIFI", "bssid": "BB:CC:DD:EE:FF:01", "description": "Router HCM", "require_bssid": true}
   ],
   "validation_mode": "strict"
 }'),
('Nhà máy Bắc Ninh', 'KCN Quế Võ, Bắc Ninh', 21.1213, 106.1621, 200,
 '{
   "networks": [],
   "validation_mode": "gps_only"
 }');

-- Sample work shifts
INSERT INTO attendance.work_shifts (name, start_time, end_time, days_of_week) VALUES
('Ca hành chính', '08:00', '17:00', '[1,2,3,4,5]'),
('Ca sáng', '06:00', '14:00', '[1,2,3,4,5,6]'),
('Ca chiều', '14:00', '22:00', '[1,2,3,4,5,6]'),
('Ca đêm', '22:00', '06:00', '[1,2,3,4,5,6]');

-- Sample leave types
INSERT INTO attendance.leave_types (name, code, max_days_per_year, is_paid) VALUES
('Nghỉ phép năm', 'AL', 12, true),
('Nghỉ ốm', 'SL', 30, true),
('Nghỉ thai sản', 'ML', 180, true),
('Nghỉ không lương', 'UL', 0, false);

-- Sample public holidays (Vietnam 2024)
INSERT INTO attendance.public_holidays (name, holiday_date, holiday_type, overtime_rate, description) VALUES
-- Nghỉ lễ quốc gia 2024
('Tết Dương lịch', '2024-01-01', 'national', 3.00, 'Nghỉ lễ Tết Dương lịch'),
('Tết Nguyên đán', '2024-02-10', 'national', 3.00, 'Mùng 1 Tết Nguyên đán'),
('Tết Nguyên đán', '2024-02-11', 'national', 3.00, 'Mùng 2 Tết Nguyên đán'), 
('Tết Nguyên đán', '2024-02-12', 'national', 3.00, 'Mùng 3 Tết Nguyên đán'),
('Tết Nguyên đán', '2024-02-13', 'national', 3.00, 'Mùng 4 Tết Nguyên đán'),
('Tết Nguyên đán', '2024-02-14', 'national', 3.00, 'Mùng 5 Tết Nguyên đán'),
('Giỗ tổ Hùng Vương', '2024-04-18', 'national', 2.00, 'Giỗ tổ Hùng Vương'),
('Giải phóng miền Nam', '2024-04-30', 'national', 2.00, 'Ngày Giải phóng miền Nam'),
('Quốc tế Lao động', '2024-05-01', 'national', 2.00, 'Ngày Quốc tế Lao động'),
('Quốc khánh', '2024-09-02', 'national', 2.00, 'Ngày Quốc khánh'),

-- Nghỉ lễ công ty
('Ngày thành lập công ty', '2024-03-15', 'company', 1.50, 'Kỷ niệm thành lập công ty'),
('Team building thường niên', '2024-12-20', 'company', 1.00, 'Ngày team building toàn công ty'),

-- Nghỉ lễ địa phương
('Ngày giải phóng Hà Nội', '2024-10-10', 'regional', 1.50, 'Ngày giải phóng thủ đô Hà Nội');

-- Cập nhật áp dụng cho địa điểm cụ thể
UPDATE attendance.public_holidays 
SET applies_to_locations = '[1]'::jsonb  -- Chỉ áp dụng cho location_id = 1 (Văn phòng HN)
WHERE name = 'Ngày giải phóng Hà Nội';

-- Sample preapprovals (cần có employee_id thực tế để test)
INSERT INTO attendance.attendance_preapprovals (
    employee_id, request_type, requested_date, 
    original_check_in, requested_check_in,
    reason, urgency_level, status
) VALUES 
-- Xin đến muộn do khẩn cấp
(1, 'late_arrival', CURRENT_DATE + INTERVAL '1 day', 
 '08:00:00', '10:00:00',
 'Vợ sinh con, cần đưa vào bệnh viện', 'emergency', 'pending'),

-- Xin về sớm cho họp phụ huynh  
(1, 'early_leave', CURRENT_DATE + INTERVAL '2 days',
 '17:00:00', '15:30:00', 
 'Họp phụ huynh ở trường con', 'normal', 'pending'),

-- Xin thay đổi cả hai (đến muộn và về sớm)
(1, 'schedule_adjustment', CURRENT_DATE + INTERVAL '3 days',
 '08:00:00', '09:30:00',
 'Khám sức khỏe định kỳ', 'normal', 'approved');

-- Cập nhật thêm thông tin cho schedule_adjustment
UPDATE attendance.attendance_preapprovals 
SET original_check_out = '17:00:00',
    requested_check_out = '16:00:00',
    approved_by = 1,
    approved_at = NOW()
WHERE request_type = 'schedule_adjustment';

-- Sample attendance settings
INSERT INTO attendance.attendance_settings (setting_key, setting_value, description) VALUES
('max_daily_overtime_hours', '4', 'Số giờ tăng ca tối đa trong ngày'),
('gps_accuracy_threshold', '50', 'Ngưỡng độ chính xác GPS (mét)'),
('auto_checkout_enabled', 'true', 'Tự động checkout khi hết giờ làm'),
('notification_late_threshold', '15', 'Gửi thông báo khi đi trễ quá X phút'),
('wifi_validation_timeout', '10', 'Timeout validation WiFi (giây)'),
('wifi_fallback_to_ssid', 'true', 'Cho phép fallback về SSID nếu BSSID fail'),
('fraud_detection_enabled', 'true', 'Bật tính năng phát hiện gian lận'),
('suspicious_location_threshold', '500', 'Ngưỡng báo động vị trí khả nghi (mét)'),
('holiday_overtime_auto_calc', 'true', 'Tự động tính overtime rate theo ngày lễ'),
('exclude_holidays_from_leave', 'true', 'Không tính ngày lễ vào nghỉ phép'),
('preapproval_auto_apply', 'true', 'Tự động áp dụng preapproval khi được duyệt'),
('preapproval_emergency_threshold', '24', 'Thời gian tối thiểu để xin emergency approval (giờ)'),
('preapproval_notification_enabled', 'true', 'Gửi thông báo khi có preapproval request'),
('preapproval_max_hours_advance', '720', 'Thời gian tối đa có thể xin phép trước (giờ - 30 ngày)');

-- ============================================================
-- COMMENTS
-- ============================================================

COMMENT ON SCHEMA attendance IS 'Schema chấm công tích hợp app mobile và máy chấm vân tay/khuôn mặt';
COMMENT ON TABLE attendance.workplace_locations IS 'Địa điểm làm việc với điều kiện GPS/WiFi';
COMMENT ON COLUMN attendance.workplace_locations.allowed_wifi_networks IS 'JSON object: {"networks":[{"ssid":"WIFI_NAME","bssid":"AA:BB:CC:DD:EE:FF","require_bssid":true}],"validation_mode":"strict/flexible/ssid_only"}';
COMMENT ON COLUMN attendance.workplace_locations.require_gps IS 'Bắt buộc kiểm tra GPS khi chấm công';
COMMENT ON COLUMN attendance.workplace_locations.require_wifi IS 'Bắt buộc kết nối WiFi khi chấm công';
COMMENT ON TABLE attendance.work_shifts IS 'Định nghĩa ca làm việc';
COMMENT ON TABLE attendance.shift_assignments IS 'Phân ca theo phòng ban/chức vụ/nhân viên';
COMMENT ON TABLE attendance.attendance_sessions IS 'Từng phiên chấm công - cặp check-in/check-out riêng biệt';
COMMENT ON TABLE attendance.attendance_records IS 'Bản ghi chấm công chính - tích hợp app và máy chấm';
COMMENT ON COLUMN attendance.attendance_records.check_in_wifi_data IS 'JSON WiFi check-in: {"ssid":"WIFI_NAME","bssid":"AA:BB:CC:DD:EE:FF","validated":true,"validation_method":"strict"}';
COMMENT ON COLUMN attendance.attendance_records.check_out_wifi_data IS 'JSON WiFi check-out: {"ssid":"WIFI_NAME","bssid":"AA:BB:CC:DD:EE:FF","validated":true,"validation_method":"strict"}';
COMMENT ON COLUMN attendance.attendance_records.mobile_device_info IS 'JSON thông tin thiết bị: {"device_id":"uuid","model":"iPhone 15","os_version":"17.0","app_version":"1.0.0"}';
COMMENT ON TABLE attendance.leave_requests IS 'Đơn xin nghỉ phép';
COMMENT ON TABLE attendance.public_holidays IS 'Ngày nghỉ lễ, tết với tỷ lệ overtime và phạm vi áp dụng';
COMMENT ON TABLE attendance.attendance_preapprovals IS 'Xin phép trước khi chấm công - đến muộn, về sớm, thay đổi lịch';
COMMENT ON TABLE attendance.monthly_attendance_summaries IS 'Chốt công hàng tháng để tính lương';
COMMENT ON TABLE attendance.device_logs IS 'Log chi tiết hoạt động chấm công từ mọi thiết bị';

-- ============================================================
-- COMPLETION
-- ============================================================

SELECT 'Attendance schema created successfully! Total tables: 18' AS result; 