-- ============================================================
-- NOTIFICATION & EVENTS MANAGEMENT SYSTEM DATABASE SCHEMA
-- ============================================================
-- Schema: notification
-- Dependencies: public schema (employees, departments), attendance schema (public_holidays)
-- Framework: Spring Boot với Spring Data JPA Auditing
-- 
-- Features:
-- - Multi-channel notifications (FCM, Email, In-app)
-- - Smart targeting (department, job level, individual)
-- - Template system for automation
-- - Events & calendar management
-- - Analytics and tracking
-- - User preferences management
-- ============================================================

-- Create notification schema
CREATE SCHEMA IF NOT EXISTS notification;

-- ============================================================
-- ENUM TYPES
-- ============================================================

CREATE TYPE notification.notification_type AS ENUM (
    'attendance', 'training', 'leave', 'overtime', 'payroll', 
    'meeting', 'deadline', 'birthday', 'holiday', 'general', 
    'system', 'urgent'
);

CREATE TYPE notification.notification_status AS ENUM ('pending', 'sent', 'delivered', 'read', 'clicked', 'failed');
CREATE TYPE notification.notification_priority AS ENUM ('low', 'normal', 'high', 'urgent');
CREATE TYPE notification.delivery_channel AS ENUM ('fcm', 'email', 'in_app', 'sms');
CREATE TYPE notification.targeting_type AS ENUM ('broadcast', 'department', 'job_level', 'individual', 'custom');
CREATE TYPE notification.template_trigger AS ENUM ('manual', 'scheduled', 'event_based', 'workflow');

CREATE TYPE notification.event_type AS ENUM (
    'meeting', 'birthday', 'training', 'holiday', 'deadline', 
    'company', 'team_building', 'maintenance', 'announcement'
);

CREATE TYPE notification.event_status AS ENUM ('active', 'cancelled', 'postponed', 'completed');
CREATE TYPE notification.event_visibility AS ENUM ('public', 'internal', 'department', 'private');
CREATE TYPE notification.participation_response AS ENUM ('pending', 'accepted', 'declined', 'maybe', 'no_response');
CREATE TYPE notification.attendance_status AS ENUM ('attended', 'absent', 'partial', 'not_applicable');

-- ============================================================
-- 1. FCM TOKENS MANAGEMENT - Quản lý Firebase tokens
-- ============================================================

CREATE TABLE notification.fcm_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INTEGER NOT NULL,
    
    -- Token information
    fcm_token VARCHAR(500) NOT NULL,
    platform VARCHAR(20) NOT NULL, -- 'android', 'ios', 'web'
    device_id VARCHAR(200),
    device_name VARCHAR(100),
    device_model VARCHAR(100),
    os_version VARCHAR(50),
    app_version VARCHAR(20),
    
    -- Status tracking
    is_active BOOLEAN DEFAULT true,
    last_used_at TIMESTAMP,
    error_count INTEGER DEFAULT 0,
    last_error_message TEXT,
    
    -- Spring Boot Audit columns
    created_by VARCHAR(50),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_by VARCHAR(50),
    last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Constraints
    CONSTRAINT unique_employee_device UNIQUE (employee_id, device_id)
);

COMMENT ON TABLE notification.fcm_tokens IS 'Quản lý Firebase Cloud Messaging tokens cho từng thiết bị';
COMMENT ON COLUMN notification.fcm_tokens.fcm_token IS 'FCM registration token từ Firebase SDK';
COMMENT ON COLUMN notification.fcm_tokens.device_id IS 'Unique identifier của thiết bị (UUID)';
COMMENT ON COLUMN notification.fcm_tokens.error_count IS 'Số lần gửi FCM thất bại liên tiếp';

-- ============================================================
-- 2. NOTIFICATION TEMPLATES - Template thông báo
-- ============================================================

CREATE TABLE notification.notification_templates (
    id VARCHAR(50) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    
    -- Template classification
    notification_type notification.notification_type NOT NULL,
    category VARCHAR(50),
    trigger_type notification.template_trigger DEFAULT 'manual',
    
    -- Template content
    title_template VARCHAR(200) NOT NULL,
    message_template TEXT NOT NULL,
    short_message_template VARCHAR(500), -- For FCM payload
    action_url_template TEXT,
    action_text VARCHAR(100),
    
    -- Default settings
    priority notification.notification_priority DEFAULT 'normal',
    channels notification.delivery_channel[] DEFAULT '{fcm,in_app}',
    is_actionable BOOLEAN DEFAULT false,
    
    -- Targeting defaults
    targeting_type notification.targeting_type DEFAULT 'broadcast',
    target_departments JSONB DEFAULT '[]'::jsonb,
    target_job_levels JSONB DEFAULT '[]'::jsonb,
    target_conditions JSONB, -- Custom targeting conditions
    
    -- Automation settings
    trigger_events JSONB, -- ['attendance_late', 'leave_approved']
    trigger_conditions JSONB, -- Conditions to send
    schedule_expression VARCHAR(100), -- Cron expression for scheduled
    
    -- Template variables
    variables_schema JSONB, -- JSON schema for validation
    sample_variables JSONB, -- Sample data for testing
    
    -- Status
    is_active BOOLEAN DEFAULT true,
    version INTEGER DEFAULT 1,
    
    -- Spring Boot Audit columns
    created_by VARCHAR(50),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_by VARCHAR(50),
    last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE notification.notification_templates IS 'Template thông báo cho automation và standardization';
COMMENT ON COLUMN notification.notification_templates.channels IS 'Array các kênh gửi: {fcm,email,in_app,sms}';
COMMENT ON COLUMN notification.notification_templates.trigger_events IS 'Events trigger template: ["attendance_late", "training_deadline"]';
COMMENT ON COLUMN notification.notification_templates.variables_schema IS 'JSON schema validation cho template variables';

-- ============================================================
-- 3. NOTIFICATIONS - Bảng thông báo chính
-- ============================================================

CREATE TABLE notification.notifications (
    id VARCHAR(50) PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    message TEXT NOT NULL,
    short_message VARCHAR(500), -- For push notification
    
    -- Classification
    notification_type notification.notification_type NOT NULL DEFAULT 'general',
    category VARCHAR(50),
    priority notification.notification_priority NOT NULL DEFAULT 'normal',
    
    -- Content & Actions
    action_url TEXT,
    action_text VARCHAR(100),
    image_url VARCHAR(500),
    metadata JSONB,
    
    -- Sender information
    sender_id VARCHAR(50),
    sender_name VARCHAR(100),
    sender_type VARCHAR(20) DEFAULT 'system', -- 'system', 'user', 'external'
    
    -- Timing
    scheduled_for TIMESTAMP,
    expires_at TIMESTAMP,
    
    -- Targeting
    targeting_type notification.targeting_type DEFAULT 'broadcast',
    target_departments JSONB DEFAULT '[]'::jsonb,
    target_job_levels JSONB DEFAULT '[]'::jsonb,
    target_employees JSONB DEFAULT '[]'::jsonb,
    targeting_conditions JSONB, -- Advanced targeting logic
    
    -- Delivery settings
    channels notification.delivery_channel[] DEFAULT '{fcm,in_app}',
    
    -- Flags
    is_actionable BOOLEAN DEFAULT false,
    is_important BOOLEAN DEFAULT false, -- Show in home dashboard
    is_draft BOOLEAN DEFAULT false,
    
    -- Processing status
    status VARCHAR(20) DEFAULT 'draft', -- 'draft', 'scheduled', 'sending', 'sent', 'failed'
    processing_started_at TIMESTAMP,
    processing_completed_at TIMESTAMP,
    
    -- Analytics counters
    total_recipients INTEGER DEFAULT 0,
    total_sent INTEGER DEFAULT 0,
    total_delivered INTEGER DEFAULT 0,
    total_read INTEGER DEFAULT 0,
    total_clicked INTEGER DEFAULT 0,
    total_failed INTEGER DEFAULT 0,
    
    -- Template reference
    template_id VARCHAR(50),
    template_variables JSONB,
    
    -- Spring Boot Audit columns
    created_by VARCHAR(50),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_by VARCHAR(50),
    last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE notification.notifications IS 'Bảng thông báo chính với multi-channel delivery';
COMMENT ON COLUMN notification.notifications.channels IS 'Array kênh gửi: {fcm,email,in_app,sms}';
COMMENT ON COLUMN notification.notifications.targeting_conditions IS 'JSON logic cho advanced targeting';
COMMENT ON COLUMN notification.notifications.template_variables IS 'Variables data used with template';

-- ============================================================
-- 4. NOTIFICATION RECIPIENTS - Chi tiết người nhận
-- ============================================================

CREATE TABLE notification.notification_recipients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id VARCHAR(50) NOT NULL,
    employee_id INTEGER NOT NULL,
    
    -- Delivery per channel
    fcm_status notification.notification_status DEFAULT 'pending',
    fcm_sent_at TIMESTAMP,
    fcm_delivered_at TIMESTAMP,
    fcm_token_used VARCHAR(500),
    
    email_status notification.notification_status DEFAULT 'pending',
    email_sent_at TIMESTAMP,
    email_delivered_at TIMESTAMP,
    email_address_used VARCHAR(100),
    
    in_app_status notification.notification_status DEFAULT 'pending',
    in_app_sent_at TIMESTAMP,
    in_app_read_at TIMESTAMP,
    in_app_clicked_at TIMESTAMP,
    
    sms_status notification.notification_status DEFAULT 'pending',
    sms_sent_at TIMESTAMP,
    sms_delivered_at TIMESTAMP,
    phone_number_used VARCHAR(20),
    
    -- Overall interaction
    first_read_at TIMESTAMP,
    first_clicked_at TIMESTAMP,
    
    -- Device information
    read_device_type VARCHAR(20),
    read_platform VARCHAR(20),
    clicked_device_type VARCHAR(20),
    
    -- Error handling
    error_messages JSONB DEFAULT '{}'::jsonb, -- Per channel errors
    retry_count INTEGER DEFAULT 0,
    
    -- Spring Boot Audit columns
    created_by VARCHAR(50),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_by VARCHAR(50),
    last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Constraints
    CONSTRAINT unique_notification_employee UNIQUE (notification_id, employee_id)
);

COMMENT ON TABLE notification.notification_recipients IS 'Chi tiết delivery status cho từng người nhận theo channel';
COMMENT ON COLUMN notification.notification_recipients.error_messages IS 'JSON errors per channel: {"fcm":"Invalid token","email":"Bounced"}';

-- ============================================================
-- 5. USER NOTIFICATION PREFERENCES - Cài đặt người dùng
-- ============================================================

CREATE TABLE notification.user_notification_preferences (
    employee_id INTEGER PRIMARY KEY,
    
    -- Global preferences
    email_notifications BOOLEAN DEFAULT true,
    fcm_notifications BOOLEAN DEFAULT true,
    in_app_notifications BOOLEAN DEFAULT true,
    sms_notifications BOOLEAN DEFAULT false,
    
    -- Type-specific preferences
    attendance_notifications BOOLEAN DEFAULT true,
    training_notifications BOOLEAN DEFAULT true,
    leave_notifications BOOLEAN DEFAULT true,
    overtime_notifications BOOLEAN DEFAULT true,
    payroll_notifications BOOLEAN DEFAULT true,
    meeting_notifications BOOLEAN DEFAULT true,
    deadline_notifications BOOLEAN DEFAULT true,
    birthday_notifications BOOLEAN DEFAULT true,
    holiday_notifications BOOLEAN DEFAULT true,
    general_notifications BOOLEAN DEFAULT true,
    system_notifications BOOLEAN DEFAULT true,
    urgent_notifications BOOLEAN DEFAULT true,
    
    -- Priority filtering
    minimum_priority notification.notification_priority DEFAULT 'low',
    only_actionable BOOLEAN DEFAULT false,
    only_important BOOLEAN DEFAULT false,
    
    -- Quiet hours
    quiet_hours_enabled BOOLEAN DEFAULT false,
    quiet_start_time TIME DEFAULT '22:00:00',
    quiet_end_time TIME DEFAULT '07:00:00',
    quiet_days JSONB DEFAULT '[]'::jsonb, -- [0,6] for Sunday, Saturday
    
    -- Rate limiting
    max_notifications_per_hour INTEGER DEFAULT 20,
    max_notifications_per_day INTEGER DEFAULT 100,
    digest_mode_enabled BOOLEAN DEFAULT false,
    digest_time TIME DEFAULT '08:00:00',
    
    -- Localization
    timezone VARCHAR(50) DEFAULT 'Asia/Ho_Chi_Minh',
    language VARCHAR(10) DEFAULT 'vi',
    date_format VARCHAR(20) DEFAULT 'dd/MM/yyyy',
    
    -- Spring Boot Audit columns
    created_by VARCHAR(50),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_by VARCHAR(50),
    last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE notification.user_notification_preferences IS 'Cài đặt thông báo cá nhân của từng nhân viên';
COMMENT ON COLUMN notification.user_notification_preferences.quiet_days IS 'JSON array ngày nghỉ: [0,6] = Chủ nhật, Thứ 7';
COMMENT ON COLUMN notification.user_notification_preferences.digest_mode_enabled IS 'Gộp thông báo thành email digest hàng ngày';

-- ============================================================
-- 6. EVENTS - Sự kiện và lịch công ty
-- ============================================================

CREATE TABLE notification.events (
    id VARCHAR(50) PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    
    -- Timing
    start_date DATE NOT NULL,
    end_date DATE,
    start_time TIME,
    end_time TIME,
    timezone VARCHAR(50) DEFAULT 'Asia/Ho_Chi_Minh',
    is_all_day BOOLEAN DEFAULT false,
    
    -- Recurrence
    is_recurring BOOLEAN DEFAULT false,
    recurrence_rule TEXT, -- RRULE format (RFC 5545)
    recurrence_end_date DATE,
    parent_event_id VARCHAR(50),
    
    -- Classification
    event_type notification.event_type NOT NULL,
    category VARCHAR(50),
    priority notification.notification_priority DEFAULT 'normal',
    
    -- Location & Access
    location VARCHAR(200),
    location_type VARCHAR(20) DEFAULT 'physical', -- 'physical', 'online', 'hybrid'
    meeting_url VARCHAR(500),
    access_code VARCHAR(50),
    room_booking_id VARCHAR(50), -- Reference to room booking system
    
    -- Participants
    organizer_id VARCHAR(50),
    organizer_name VARCHAR(100),
    max_participants INTEGER,
    is_optional BOOLEAN DEFAULT false,
    requires_approval BOOLEAN DEFAULT false,
    
    -- Targeting
    targeting_type notification.targeting_type DEFAULT 'broadcast',
    target_departments JSONB DEFAULT '[]'::jsonb,
    target_job_levels JSONB DEFAULT '[]'::jsonb,
    target_employees JSONB DEFAULT '[]'::jsonb,
    
    -- Status & Visibility
    status notification.event_status DEFAULT 'active',
    visibility notification.event_visibility DEFAULT 'internal',
    
    -- Notifications
    reminder_enabled BOOLEAN DEFAULT true,
    reminder_times JSONB DEFAULT '[15,60,1440]'::jsonb, -- Minutes before event
    auto_notification BOOLEAN DEFAULT true,
    
    -- Analytics
    total_invited INTEGER DEFAULT 0,
    total_accepted INTEGER DEFAULT 0,
    total_declined INTEGER DEFAULT 0,
    total_attended INTEGER DEFAULT 0,
    
    -- Metadata
    metadata JSONB,
    external_calendar_id VARCHAR(100), -- Google Calendar, Outlook ID
    
    -- Spring Boot Audit columns
    created_by VARCHAR(50),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_by VARCHAR(50),
    last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE notification.events IS 'Hệ thống sự kiện và lịch công ty tích hợp notification';
COMMENT ON COLUMN notification.events.reminder_times IS 'JSON array thời gian nhắc nhở (phút): [15,60,1440] = 15p, 1h, 1 ngày trước';
COMMENT ON COLUMN notification.events.recurrence_rule IS 'RRULE format theo RFC 5545 cho sự kiện lặp lại';

-- ============================================================
-- 7. EVENT PARTICIPANTS - Người tham gia sự kiện
-- ============================================================

CREATE TABLE notification.event_participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(50) NOT NULL,
    employee_id INTEGER NOT NULL,
    
    -- Invitation
    invited_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    invited_by VARCHAR(50),
    invitation_message TEXT,
    
    -- Response
    response notification.participation_response DEFAULT 'pending',
    responded_at TIMESTAMP,
    response_notes TEXT,
    
    -- Attendance tracking
    checked_in_at TIMESTAMP,
    checked_out_at TIMESTAMP,
    attendance_status notification.attendance_status DEFAULT 'not_applicable',
    attendance_notes TEXT,
    
    -- Reminders
    reminder_count INTEGER DEFAULT 0,
    last_reminder_sent TIMESTAMP,
    
    -- Spring Boot Audit columns
    created_by VARCHAR(50),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_by VARCHAR(50),
    last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Constraints
    CONSTRAINT unique_event_participant UNIQUE (event_id, employee_id)
);

COMMENT ON TABLE notification.event_participants IS 'Người tham gia sự kiện với tracking RSVP và attendance';

-- ============================================================
-- 8. NOTIFICATION ANALYTICS - Thống kê và phân tích
-- ============================================================

CREATE TABLE notification.notification_analytics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id VARCHAR(50) NOT NULL,
    
    -- Delivery metrics
    total_recipients INTEGER DEFAULT 0,
    
    -- Per channel metrics
    fcm_sent INTEGER DEFAULT 0,
    fcm_delivered INTEGER DEFAULT 0,
    fcm_failed INTEGER DEFAULT 0,
    
    email_sent INTEGER DEFAULT 0,
    email_delivered INTEGER DEFAULT 0,
    email_failed INTEGER DEFAULT 0,
    
    in_app_sent INTEGER DEFAULT 0,
    in_app_read INTEGER DEFAULT 0,
    in_app_clicked INTEGER DEFAULT 0,
    
    sms_sent INTEGER DEFAULT 0,
    sms_delivered INTEGER DEFAULT 0,
    sms_failed INTEGER DEFAULT 0,
    
    -- Calculated rates
    overall_delivery_rate DECIMAL(5,2) DEFAULT 0,
    read_rate DECIMAL(5,2) DEFAULT 0,
    click_rate DECIMAL(5,2) DEFAULT 0,
    
    -- Timing analytics
    avg_time_to_read_minutes INTEGER,
    avg_time_to_click_minutes INTEGER,
    peak_read_hour INTEGER, -- Hour with most reads
    
    -- Device breakdown
    device_breakdown JSONB, -- {"android": 45, "ios": 30, "web": 25}
    platform_performance JSONB, -- Performance per platform
    
    -- Calculated at
    calculated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Constraints
    CONSTRAINT unique_notification_analytics UNIQUE (notification_id)
);

COMMENT ON TABLE notification.notification_analytics IS 'Thống kê chi tiết performance của từng notification';
COMMENT ON COLUMN notification.notification_analytics.device_breakdown IS 'JSON phân bố thiết bị: {"android": 45, "ios": 30, "web": 25}';

-- ============================================================
-- 9. SYSTEM SETTINGS - Cấu hình hệ thống
-- ============================================================

CREATE TABLE notification.system_settings (
    setting_key VARCHAR(100) PRIMARY KEY,
    setting_value JSONB NOT NULL,
    description TEXT,
    data_type VARCHAR(20) DEFAULT 'string', -- 'string', 'integer', 'boolean', 'json'
    is_public BOOLEAN DEFAULT false, -- Client có đọc được không
    
    -- Spring Boot Audit columns
    created_by VARCHAR(50),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_by VARCHAR(50),
    last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE notification.system_settings IS 'Cấu hình hệ thống notification';

-- ============================================================
-- 10. ACTIVITY LOGS - Log hoạt động
-- ============================================================

CREATE TABLE notification.activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INTEGER,
    
    -- Action details
    action_type VARCHAR(50) NOT NULL, -- 'notification_read', 'notification_clicked', 'event_rsvp'
    entity_type VARCHAR(50), -- 'notification', 'event', 'template'
    entity_id VARCHAR(50),
    
    -- Context
    device_type VARCHAR(20),
    platform VARCHAR(20),
    app_version VARCHAR(20),
    ip_address INET,
    user_agent TEXT,
    
    -- Additional data
    metadata JSONB,
    
    -- Timestamp
    action_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Indexes will be added below
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE notification.activity_logs IS 'Log hoạt động người dùng với notification system';

-- ============================================================
-- FOREIGN KEY CONSTRAINTS TO OTHER SCHEMAS
-- ============================================================

-- References to public.employees (primary key is 'id', not 'emp_id')
ALTER TABLE notification.fcm_tokens 
ADD CONSTRAINT fk_fcm_token_employee 
FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE;

-- Note: sender_id, organizer_id, invited_by, created_by are VARCHAR fields designed for usernames/emails
-- not employee IDs, so we don't add foreign key constraints for them

ALTER TABLE notification.notification_recipients 
ADD CONSTRAINT fk_recipient_notification 
FOREIGN KEY (notification_id) REFERENCES notification.notifications(id) ON DELETE CASCADE;

ALTER TABLE notification.notification_recipients 
ADD CONSTRAINT fk_recipient_employee 
FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE;

ALTER TABLE notification.user_notification_preferences 
ADD CONSTRAINT fk_preferences_employee 
FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE;

ALTER TABLE notification.events 
ADD CONSTRAINT fk_event_parent 
FOREIGN KEY (parent_event_id) REFERENCES notification.events(id);

ALTER TABLE notification.event_participants 
ADD CONSTRAINT fk_participant_event 
FOREIGN KEY (event_id) REFERENCES notification.events(id) ON DELETE CASCADE;

ALTER TABLE notification.event_participants 
ADD CONSTRAINT fk_participant_employee 
FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE;

ALTER TABLE notification.notification_analytics 
ADD CONSTRAINT fk_analytics_notification 
FOREIGN KEY (notification_id) REFERENCES notification.notifications(id) ON DELETE CASCADE;

ALTER TABLE notification.activity_logs 
ADD CONSTRAINT fk_activity_employee 
FOREIGN KEY (employee_id) REFERENCES public.employees(id);

ALTER TABLE notification.notifications 
ADD CONSTRAINT fk_notification_template 
FOREIGN KEY (template_id) REFERENCES notification.notification_templates(id);

-- ============================================================
-- INDEXES FOR PERFORMANCE
-- ============================================================

-- FCM tokens indexes
CREATE INDEX idx_fcm_tokens_employee ON notification.fcm_tokens (employee_id);
CREATE INDEX idx_fcm_tokens_active ON notification.fcm_tokens (employee_id, is_active) WHERE is_active = true;
CREATE INDEX idx_fcm_tokens_platform ON notification.fcm_tokens (platform, is_active);
CREATE INDEX idx_fcm_tokens_last_used ON notification.fcm_tokens (last_used_at DESC);

-- Notifications indexes
CREATE INDEX idx_notifications_type_priority ON notification.notifications (notification_type, priority);
CREATE INDEX idx_notifications_status ON notification.notifications (status, scheduled_for);
CREATE INDEX idx_notifications_important ON notification.notifications (is_important, created_date DESC) WHERE is_important = true;
CREATE INDEX idx_notifications_sender ON notification.notifications (sender_id, created_date DESC);
CREATE INDEX idx_notifications_template ON notification.notifications (template_id);
CREATE INDEX idx_notifications_targeting ON notification.notifications (targeting_type);

-- Recipients indexes
CREATE INDEX idx_recipients_employee ON notification.notification_recipients (employee_id, created_date DESC);
CREATE INDEX idx_recipients_fcm_status ON notification.notification_recipients (fcm_status, fcm_sent_at);
CREATE INDEX idx_recipients_read ON notification.notification_recipients (in_app_read_at DESC) WHERE in_app_read_at IS NOT NULL;
CREATE INDEX idx_recipients_clicked ON notification.notification_recipients (in_app_clicked_at DESC) WHERE in_app_clicked_at IS NOT NULL;

-- Templates indexes
CREATE INDEX idx_templates_type ON notification.notification_templates (notification_type, is_active);
CREATE INDEX idx_templates_trigger ON notification.notification_templates (trigger_type, is_active);
CREATE INDEX idx_templates_active ON notification.notification_templates (is_active, created_date DESC);

-- Events indexes
CREATE INDEX idx_events_date_type ON notification.events (start_date, event_type);
CREATE INDEX idx_events_organizer ON notification.events (organizer_id, created_date DESC);
CREATE INDEX idx_events_status ON notification.events (status, start_date);
CREATE INDEX idx_events_upcoming ON notification.events (start_date, status) WHERE status = 'active';
CREATE INDEX idx_events_recurring ON notification.events (is_recurring, parent_event_id);

-- Event participants indexes
CREATE INDEX idx_participants_employee ON notification.event_participants (employee_id, response);
CREATE INDEX idx_participants_event_response ON notification.event_participants (event_id, response);
CREATE INDEX idx_participants_pending ON notification.event_participants (employee_id, response) WHERE response = 'pending';

-- Activity logs indexes
CREATE INDEX idx_activity_employee_time ON notification.activity_logs (employee_id, action_timestamp DESC);
CREATE INDEX idx_activity_type_time ON notification.activity_logs (action_type, action_timestamp DESC);
CREATE INDEX idx_activity_entity ON notification.activity_logs (entity_type, entity_id);

-- Analytics indexes
CREATE INDEX idx_analytics_rates ON notification.notification_analytics (read_rate DESC, click_rate DESC);
CREATE INDEX idx_analytics_calculated ON notification.notification_analytics (calculated_at DESC);

-- ============================================================
-- SAMPLE DATA
-- ============================================================

-- Sample notification templates
INSERT INTO notification.notification_templates (
    id, name, notification_type, title_template, message_template, 
    channels, is_actionable, targeting_type, priority
) VALUES 
('TMPL_ATTENDANCE_LATE', 'Thông báo đi muộn', 'attendance', 
 'Nhân viên {{employee_name}} đã đi muộn', 
 'Nhân viên {{employee_name}} ({{employee_code}}) đã check-in muộn {{late_minutes}} phút vào lúc {{check_in_time}} ngày {{work_date}}.',
 '{fcm,in_app}', false, 'department', 'normal'),

('TMPL_LEAVE_APPROVED', 'Đơn nghỉ phép được duyệt', 'leave',
 'Đơn nghỉ phép của bạn đã được duyệt',
 'Đơn nghỉ phép từ {{start_date}} đến {{end_date}} ({{total_days}} ngày) đã được {{approver_name}} duyệt.',
 '{fcm,email,in_app}', true, 'individual', 'high'),

('TMPL_BIRTHDAY_REMINDER', 'Sinh nhật nhân viên', 'birthday',
 'Hôm nay sinh nhật {{employee_name}}! 🎉',
 'Chúc mừng sinh nhật {{employee_name}} - {{department_name}}. Hãy gửi lời chúc đến đồng nghiệp nhé!',
 '{fcm,in_app}', false, 'broadcast', 'normal'),

('TMPL_MEETING_REMINDER', 'Nhắc nhở cuộc họp', 'meeting',
 'Cuộc họp sắp bắt đầu trong {{minutes_before}} phút',
 'Cuộc họp "{{meeting_title}}" sẽ bắt đầu lúc {{start_time}} tại {{location}}.',
 '{fcm,in_app}', true, 'individual', 'high'),

('TMPL_SYSTEM_MAINTENANCE', 'Bảo trì hệ thống', 'system',
 'Hệ thống sẽ bảo trì từ {{start_time}} đến {{end_time}}',
 'Để nâng cấp và cải thiện dịch vụ, hệ thống sẽ tạm ngừng hoạt động từ {{start_time}} đến {{end_time}} ngày {{maintenance_date}}.',
 '{fcm,email,in_app}', false, 'broadcast', 'urgent');

-- Sample system settings
INSERT INTO notification.system_settings (setting_key, setting_value, description, data_type) VALUES
('fcm_max_retries', '3', 'Số lần thử lại tối đa khi gửi FCM thất bại', 'integer'),
('email_max_retries', '2', 'Số lần thử lại tối đa khi gửi email thất bại', 'integer'),
('notification_batch_size', '100', 'Số lượng notification gửi trong một batch', 'integer'),
('analytics_retention_days', '90', 'Số ngày lưu trữ analytics data', 'integer'),
('digest_enabled', 'true', 'Bật tính năng email digest', 'boolean'),
('quiet_hours_respect', 'true', 'Tôn trọng giờ yên tĩnh của user', 'boolean'),
('fcm_timeout_seconds', '30', 'Timeout cho FCM request (giây)', 'integer'),
('email_timeout_seconds', '60', 'Timeout cho email sending (giây)', 'integer'),
('max_image_size_mb', '5', 'Kích thước file ảnh tối đa (MB)', 'integer'),
('emergency_notification_override', 'true', 'Bypass quiet hours cho notification urgent', 'boolean'),
('analytics_realtime_enabled', 'true', 'Bật analytics realtime', 'boolean'),
('fcm_priority_mapping', '{"low":"normal","normal":"normal","high":"high","urgent":"high"}', 'Mapping priority với FCM priority', 'json');

-- Sample events (company events)
INSERT INTO notification.events (
    id, title, description, start_date, start_time, end_time,
    event_type, organizer_name, targeting_type, auto_notification, reminder_times
) VALUES 
('EVT_COMPANY_MEETING_2024', 'Họp toàn công ty Q4/2024', 
 'Tổng kết hoạt động Q4 và định hướng 2025', 
 CURRENT_DATE + INTERVAL '7 days', '09:00:00', '11:00:00',
 'company', 'Ban Giám Đốc', 'broadcast', true, '[15,60,1440]'),

('EVT_TEAM_BUILDING_2024', 'Team building cuối năm',
 'Chương trình team building và gala dinner cuối năm',
 CURRENT_DATE + INTERVAL '30 days', '14:00:00', '22:00:00', 
 'team_building', 'Phòng Nhân sự', 'broadcast', true, '[60,1440,10080]'),

('EVT_SYSTEM_MAINTENANCE', 'Bảo trì hệ thống định kỳ',
 'Nâng cấp server và cập nhật phần mềm',
 CURRENT_DATE + INTERVAL '3 days', '02:00:00', '06:00:00',
 'maintenance', 'Phòng IT', 'broadcast', true, '[120,1440]');

-- Sample user preferences (cần employee_id thực tế)
INSERT INTO notification.user_notification_preferences (
    employee_id, 
    fcm_notifications, email_notifications,
    meeting_notifications, system_notifications,
    quiet_hours_enabled, quiet_start_time, quiet_end_time,
    max_notifications_per_hour
) VALUES 
(1, true, true, true, true, true, '22:00:00', '07:00:00', 15),
(2, true, false, true, true, false, '22:00:00', '07:00:00', 20);

-- ============================================================
-- VIEWS FOR COMMON QUERIES
-- ============================================================

-- View for unread notifications count per user
CREATE VIEW notification.user_unread_counts AS
SELECT 
    nr.employee_id,
    COUNT(*) as total_unread,
    COUNT(*) FILTER (WHERE n.is_important = true) as important_unread,
    COUNT(*) FILTER (WHERE n.priority = 'urgent') as urgent_unread
FROM notification.notification_recipients nr
JOIN notification.notifications n ON nr.notification_id = n.id
WHERE nr.in_app_status IN ('sent', 'delivered') 
    AND nr.in_app_read_at IS NULL
    AND n.status = 'sent'
GROUP BY nr.employee_id;

-- View for upcoming events (next 30 days)
CREATE VIEW notification.upcoming_events AS
SELECT 
    e.*,
    ep.response as user_response,
    ep.employee_id
FROM notification.events e
LEFT JOIN notification.event_participants ep ON e.id = ep.event_id
WHERE e.start_date BETWEEN CURRENT_DATE AND CURRENT_DATE + INTERVAL '30 days'
    AND e.status = 'active'
ORDER BY e.start_date, e.start_time;

-- View for notification performance summary
CREATE VIEW notification.notification_performance AS
SELECT 
    n.id,
    n.title,
    n.notification_type,
    n.priority,
    n.created_date,
    na.total_recipients,
    COALESCE(na.overall_delivery_rate, 0) as delivery_rate,
    COALESCE(na.read_rate, 0) as read_rate,
    COALESCE(na.click_rate, 0) as click_rate
FROM notification.notifications n
LEFT JOIN notification.notification_analytics na ON n.id = na.notification_id
WHERE n.status = 'sent'
ORDER BY n.created_date DESC;

-- ============================================================
-- COMMENTS
-- ============================================================

COMMENT ON SCHEMA notification IS 'Schema quản lý notification và events với multi-channel delivery';
COMMENT ON VIEW notification.user_unread_counts IS 'View số lượng notification chưa đọc per user';
COMMENT ON VIEW notification.upcoming_events IS 'View sự kiện sắp tới trong 30 ngày';
COMMENT ON VIEW notification.notification_performance IS 'View performance summary của notifications';

-- ============================================================
-- COMPLETION
-- ============================================================

SELECT 'Notification schema created successfully! Total tables: 10, Views: 3' AS result; 