global:
  # SMTP Configuration
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@personaai.local'
  smtp_auth_username: ''
  smtp_auth_password: ''
  smtp_require_tls: false

# Routing configuration
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'default'
  routes:
    # Critical alerts
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 5s
      repeat_interval: 5m
    
    # PersonaAI app specific alerts
    - match:
        service: personaai-android
      receiver: 'personaai-team'
      group_wait: 30s
      repeat_interval: 30m

# Alert receivers
receivers:
  # Default receiver
  - name: 'default'
    webhook_configs:
      - url: 'http://localhost:5001/webhook'
        send_resolved: true

  # Critical alerts - immediate notification
  - name: 'critical-alerts'
    email_configs:
      - to: 'ops-team@personaai.local'
        subject: '🚨 CRITICAL: PersonaAI Alert'
        html: |
          <h2>Critical Alert</h2>
          {{ range .Alerts }}
          <p><strong>Alert:</strong> {{ .Annotations.summary }}</p>
          <p><strong>Description:</strong> {{ .Annotations.description }}</p>
          <p><strong>Severity:</strong> {{ .Labels.severity }}</p>
          <hr>
          {{ end }}
    webhook_configs:
      - url: 'http://localhost:5001/critical'
        send_resolved: true

  # PersonaAI team notifications
  - name: 'personaai-team'
    email_configs:
      - to: 'personaai-team@kienlongbank.com'
        subject: '📱 PersonaAI App Alert: {{ .GroupLabels.alertname }}'
        html: |
          <h3>PersonaAI Android App Alert</h3>
          <table border="1">
            <tr><th>Alert</th><th>Severity</th><th>Description</th></tr>
            {{ range .Alerts }}
            <tr>
              <td>{{ .Annotations.summary }}</td>
              <td>{{ .Labels.severity }}</td>
              <td>{{ .Annotations.description }}</td>
            </tr>
            {{ end }}
          </table>
          <p><a href="{{ .ExternalURL }}">View in Alertmanager</a></p>

# Inhibition rules - prevent spam
inhibit_rules:
  # Mute warning if critical firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
  
  # Mute instance alerts if service down
  - source_match:
      alertname: 'InstanceDown'
    target_match_re:
      alertname: '.*'
    equal: ['instance'] 