receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

  memory_limiter:
    limit_mib: 512
    check_interval: 1s

  resource:
    attributes:
      - key: service.name
        value: personaai-android
        action: upsert

exporters:
  # Prometheus for metrics
  prometheus:
    endpoint: "0.0.0.0:8889"

  # Loki for logs - Simple format
  loki:
    endpoint: http://loki:3100/loki/api/v1/push

  # Tempo for traces
  otlp/tempo:
    endpoint: http://tempo:4317
    tls:
      insecure: true

  # Debug for development
  debug:
    verbosity: basic

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [otlp/tempo, debug]

    metrics:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [prometheus, debug]

    logs:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [loki, debug] 