server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    # Simplified batch settings
    batch_wait: 1s
    batch_size: 1048576  # 1MB

scrape_configs:
  # Chỉ collect logs quan trọng từ monitoring containers
  - job_name: monitoring_containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: monitoring_logs
          __path__: /var/lib/docker/containers/*/*log

    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            time: time
      
      - timestamp:
          format: RFC3339Nano
          source: time
      
      - output:
          source: output

  # System logs - chỉ critical errors
  - job_name: system_errors
    static_configs:
      - targets:
          - localhost
        labels:
          job: system_logs
          __path__: /var/log/syslog

    pipeline_stages:
      # Chỉ lấy ERROR và CRITICAL logs
      - match:
          selector: '{job="system_logs"}'
          stages:
            - regex:
                expression: '(?i).*(error|critical|fatal|panic).*'
            - labels:
                level: error

  # Docker daemon logs
  - job_name: dockerlogs
    static_configs:
      - targets:
          - localhost
        labels:
          job: dockerlogs
          __path__: /var/log/docker.log 